### ISSUE TITLE
part of the tutorial is missing

### ISSUE THREAD

**Issue by ORESoftware** [happypoulp/redux-tutorial#113]
I have been through this tutorial a few times; although redux is not necessarily tied to React, let's assume it's coupled for a moment.

What I am missing is how to create an action from a react component and dispatch that action to a redux store. There is no code in the tutorial that I have seen that shows this part and it's sorely missing.

Furthermore, it would also be nice to see how to subscribe to a redux store from a react component

**Comment by happypoulp** [comment]
Hi,

Isn't what you're searching in this part of the tutorial https://github.com/happypoulp/redux-tutorial/blob/master/11_Provider-and-connect.js ?

**Comment by ORESoftware** [comment]
ummm, no that link didn't have that


I am looking for something like:


```js
export default React.createClass({
  
   getInitialState: function(){

     return {};
   },

  componentDidMount: function(){
    this.unsubscribe =  reduxStore...

   },

  handleOnClick: function(){

      // create action and dispatch to store
   },

   render: function(){
       return (<div></div>)
   }

});

```

sorry I can't remember the exact syntax, and sorry I should have put this code in my original question. Is an example like this available in this tutorial?

**Comment by happypoulp** [comment]
Hi,

It looks like you're searching for a way to manually link Redux and React together.

You are correct this manual process is not demonstrated in this tutorial because instead, in part 11 of the tutorial (https://github.com/happypoulp/redux-tutorial/blob/master/11_Provider-and-connect.js is the introduction for a more complete example of how React and Redux can work together - **complete code for part 11 is here: https://github.com/happypoulp/redux-tutorial/tree/master/11_src/src**), you can find the recommended "official" way to work with Redux in React via `connect` higher order function and via `Provider` higher order component (both delivered by [react-redux](https://github.com/reactjs/react-redux)).

Specifically, a demonstration about how to call an action from a component can be found here https://github.com/happypoulp/redux-tutorial/blob/master/11_src/src/home.jsx#L70 and the subscription / un-subscription process is handled by `connect` itself.

If your intention is really to go with Redux + React **without react-redux bindings**, I can only suggest to have a look at react-redux source code directly as it might explains better that me how you could achieve that.

Hope that helps.

**Comment by ORESoftware** [comment]
thanks yep it helps, sorry I didn't respond earlier but I will use this
