### ISSUE TITLE
Can't run npm run example 01_simple-action-creator.js

### ISSUE THREAD

**Issue by qiuyuntao** [happypoulp/redux-tutorial#88]
When I use command `npm run example 01_simple-action-creator.js` as the `README.md` write. There is some errors in my terminal.

![41ebe25d13ea8db5fc34ad4089fc3812](http://chuantu.biz/t2/23/1451836219x-1566638305.png)

![41ebe25d13ea8db5fc34ad4089fc3813](https://cloud.githubusercontent.com/assets/8157476/12079434/b98f6bca-b273-11e5-9665-4d75b56d6455.png)

The error said, I need to upgrade my node and npm version. But my node and npm version is the laste.

![screen shot 2016-01-03 at 11 31 03 pm](https://cloud.githubusercontent.com/assets/8157476/12079436/bf56af1e-b273-11e5-98c8-c983da04405e.png)

**Comment by happypoulp** [comment]
This does not seem to be an error with `node` or `npm`. The message about making sure to have latest node and npm is a default message output from npm when something goes wrong using a npm command.

Looking at part of the stack trace you provided, the error seems to be issued from babel-core package. 
1. Can you give me the output of `./node_modules/.bin/babel-node --version`?
2. And can you also try to run `babel-node --version` (to confirm that you're not using a globally installed babel-node)?

**Comment by qiuyuntao** [comment]
`./node_modules/.bin/babel-node --version` is `5.3.1`
`babel-node --version` is `6.3.17`

![Alt text](http://chuantu.biz/t2/23/1451916411x-1566638305.png)

**Comment by happypoulp** [comment]
Ok, so you seem to have a globally installed version of babel that is more recent than the one this tutorial intend to use. I am not sure if this issue actually happens because of that version difference)... To confirm it, could you please try to run:
1.  `./node_modules/.bin/babel-node --stage=0 01_simple-action-creator.js`
2. `babel-node --stage=0 01_simple-action-creator.js`

 and tell me what each of those produce?

**Comment by qiuyuntao** [comment]
- use `./node_modules/.bin/babel-node --stage=0 01_simple-action-creator.js` command

![Alt text](http://chuantu.biz/t2/23/1451960897x-954498997.png)
- use `babel-node --stage=0 01_simple-action-creator.js` command

![Alt text](http://chuantu.biz/t2/23/1451960910x-954498997.png)

**Comment by happypoulp** [comment]
Ok, it seems you're using `babel-node` from `redux-tutorial/node_modules` which is the intended behavior but I am a bit stuck about why you would have this error. This error only happens if you're using an option in the .babelrc file that is unknown to babel (and the only option specified is `stage: 0` which is a valid option)...
Did you made any modifications to redux-tutorial/.babelrc locally?

**Comment by qiuyuntao** [comment]
I have do noting in `redux-tutorial/.babelrc`

```
{
  "stage": 0
}
```

That is the code in thie file.

**Comment by happypoulp** [comment]
Could you go into `node_modules/babel-core/lib/transformation/file/options/option-manager.js` and patch this file like this:

Line 126:
Replace

``` javascript
if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
```

by

``` javascript
if (!option) {
  console.log('option not found', key, opts, alias);
  this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
}
```

and then run `npm run example 01_simple-action-creator.js` and give me the output.

Thanks.

**Comment by qiuyuntao** [comment]
I have changed the code like you said. And after run `npm run example 01_simple-action-creator.js`, the result is images below.
![Alt text](http://chuantu.biz/t2/23/1452000410x1822611387.png)
![Alt text](http://chuantu.biz/t2/23/1452000417x1822611387.png)

**Comment by happypoulp** [comment]
Ok, so we got the answer :). It seems somehow that you got a `.babelrc` file defined in your user home directory (`/Users/qiuyuntao/.babelrc`) and while I got no idea why, this `.babelrc` takes precedence over the one present in this tutorial. The issue is that `/Users/qiuyuntao/.babelrc` is a babel6 one and contains options ({presets: ['es2015']}) that are unknown to babel5 (this tutorial uses babel5).
I'll try to understand why this happens but meanwhile, you can rename `/Users/qiuyuntao/.babelrc` to `/Users/qiuyuntao/.babelrc_new` and you should be able to run tutorial examples correctly.
Tell if this works so that I can move on to search a fix.
PS: when you're done rename back your `/Users/qiuyuntao/.babelrc_new` file to `/Users/qiuyuntao/.babelrc`.
Thanks.

**Comment by qiuyuntao** [comment]
After I rename the file `/Users/qiuyuntao/.babelrc` to `/Users/qiuyuntao/.babelrc_new`, it will wrok as we want in thie tutorial.
And what's the different between  `/Users/qiuyuntao/.babelrc` and `/Users/qiuyuntao/.babelrc_new`?

 `/Users/qiuyuntao/.babelrc` is used for `babel 6` and ````/Users/qiuyuntao/.babelrc_new` is used for `babel 5`?

This turorial is run in `bebel 5` environment，but in my computer, it run in `bebel 6` global environment, not run in project environment in `babel 5`?

**Comment by happypoulp** [comment]
> And what's the different between /Users/qiuyuntao/.babelrc and /Users/qiuyuntao/.babelrc_new?

No difference, it is just a nasty trick to make `/Users/qiuyuntao/.babelrc_new` file undetectable by babel (so that when running `babel-node some_file.js`, babel will not "see" your `/Users/qiuyuntao/.babelrc_new` file because it expects it to be called exactly `.babelrc`).

> /Users/qiuyuntao/.babelrc is used for babel 6 and ```/Users/qiuyuntao/.babelrc_new is used for babel 5?

By default both babel5 and babel6 can use a `.babelrc` conf file (which has to be called exactly like that) but options in it are different and non-compatible. The renaming to `.babelrc_new` is a **temporary fix** to allow you to play with the tutorial.

> This turorial is run in bebel 5 environment，but in my computer, it run in bebel 6 global environment, not run in project environment in babel 5?

I am not sure I understand your question but I'll try to answer. Yes this tutorial is using babel5. Babel5 was installed locally to this tutorial inside node_modules when you ran `npm install`. Theorically your global babel6 install should not conflict with the babel5 installed in this tutorial. The issue (that I managed to reproduce by the way) is that your "global" `.babelrc` is used in place of the tutorial `.babelrc`. I think this is a babel issue, I'll investigate that. The "fix" I proposed you is really just a temporary one since it makes your global `.babelrc` to be unseen by both tutorial's babel5 and your global babel6 (thanks to that, babel5's tutorial only see the `.babelrc` file of the tutorial and use it as expected). That why once you're done with running through the tutorial, you should rename back your global `.babelrc_new` to `.babelrc` because if you don't, your global babel won't "see" this file and it may break your experience with babel6 in other projects.

I'll try to provide a fix for the tutorial soon, that does not involve the renaming I asked you to do since it is obviously not an acceptable solution, but for the time being you can move on on the tutorial.

Hope this clarifies everything.

**Comment by happypoulp** [comment]
Found a fix via an undocumented property `breakConfig` (http://stackoverflow.com/questions/32540598/disable-babelrc-inheritance).

You should be able to pull latest `master` of the tutorial, rename back your global config from `.babelrc_new` to `.babelrc` and still have the tutorial to work properly.

**Comment by qiuyuntao** [comment]
thanks!
